## Numpy Array Operations

In [1]:
import numpy as np 

In [2]:
# 1D array indexing slicing 
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("with step", arr[1:8:2])
print("negative indexing", arr[-3])



Basic Slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


In [3]:
# 2D array indexing slicing 
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("specific element", arr_2d[1,2])
print("entire row",arr_2d[1])
print("entire column",arr_2d[:,1])


specific element 6
entire row [4 5 6]
entire column [2 5 8]


## sorting


In [4]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("sorted array", np.sort(unsorted))

arr_2d_unsorted= np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column", np.sort(arr_2d_unsorted, axis=0)) #frequently used 

print("sorted 2d array by rows", np.sort(arr_2d_unsorted, axis=1))




sorted array [1 1 2 3 4 5 6 9]
sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by rows [[1 3]
 [1 2]
 [2 3]]


## filter


In [5]:
numbers= np.array([1,2,3,4,5,6,7,8,9,10])
even_number= numbers[numbers %2 == 0]
print("even numbers", even_number)

even numbers [ 2  4  6  8 10]


## Filter with mask 


In [6]:
mask =numbers >5 
print("numbers greater than 5", numbers[mask])


numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [7]:
  #fancy indexing 
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers >5 ) # it stores the indices of all  element which is greater than 5
print(" NP where", numbers[where_result])



[1 3 5]
 NP where [ 6  7  8  9 10]


In [8]:
# where clause return existed np array 

condition_array = np.where(numbers >5 , "true ", "false") #it will return true in place of value of numbers array where the condition number>5 fulfill otherwise it return false 
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true ' 'true ' 'true ' 'true '
 'true ']


### Adding and removing data 


In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
Combined = np.concatenate((arr1,arr2))
print(Combined)


[1 2 3 4 5 6]


#### array compatiblity


In [10]:
a= np.array([1,2,3])
b= np.array([1,2,3])
c= np.array([1,2,3])

print("compatibility shaped", a.shape == b.shape) #to check compatibility of array 


compatibility shaped True


In [11]:
original = np.array([[1,2],[3,4]])
new_row= np.array([[5,6]])
 # adding row  vstack (vertical stack) adds row 
with_new_row= np.vstack((original,new_row))
print(original)
print(with_new_row)

#adding column  hstack(horizontal stack ) ads coloumn 
new_col =np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [12]:
arr= np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
# np.delete takes two parameter one is array and second index(index slicing ) of element to delete 
print( " array after deletion ",deleted)

 array after deletion  [1 2 4 5]
