In [13]:
import numpy as np 
from numpy import random as r


### numpy random 


In [21]:
x= r.rand()
print(x)

y= r.rand(4)
print(y)

random_array = r.randint(100,size=(5))
print(random_array)

random_2D_array= r.randint(100 , size=(2,5))
print(random_2D_array)

random_value= r.choice(random_array)
print(random_value)

random_value_with_size= r.choice(random_array, size=(2,3))
print(random_value_with_size)




0.771142578457245
[0.34077221 0.30782162 0.08326101 0.14638796]
[97 98 23 58 60]
[[33 77 69 75 84]
 [51 42 48 26 43]]
97
[[60 98 98]
 [23 58 98]]
