## numpy array and basics 
learning numpy

In [1]:
import numpy as np

creating array from list

In [2]:
arr_1d=np.array([1,2,3,4])
print("1D array:",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print( "2D array : " , arr_2d)

1D array: [1 2 3 4]
2D array :  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [3]:
py_list=[1,2,3,4]
print("python list multiplication", py_list *2)

np_array = np.array([1,2,3,4]) #element wise multiply happens 
print("numpy array multiplication ", np_array *2)


python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
numpy array multiplication  [2 4 6 8]


## creating array from scratch 


In [4]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((3,4))
print("ones array: \n", ones )

full = np.full((3,4),7)  #for constant values 
print("full array: \n", full)

random =np.random.random((2,3)) #for random values arrays
print("random array : \n",random)

sequence= np.arange(0,10,2)
print("sequence array : \n", sequence)




zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array : 
 [[0.56328488 0.79009724 0.31727027]
 [0.59120346 0.059674   0.01367333]]
sequence array : 
 [0 2 4 6 8]


### vector , Matrix and tensor

In [5]:
vector=np.array([1,2,3,4])
print("vector:",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print( "matrix: " , matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("tensor:",tensor)

vector: [1 2 3 4]
matrix:  [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### array properties

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape ", arr.shape)
print("dimensions ", arr.ndim)
print("size", arr.size)
print("datatype", arr.dtype)


shape  (2, 3)
dimensions  2
size 6
datatype int64


#### array reshaping 

In [7]:
arr = np.arange(12)
print("original array : \n", arr) 
reshaped =arr.reshape((3,4))
print("reshaped array \n ", reshaped)
flattened = reshaped.flatten()
print("flattened array " , flattened)


original array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
